# Generated by Django 6.0.6 on 2026-07-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('analytics', '0002_targetgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='target_groups',
            field=models.ManyToManyField(blank=True, related_name='users', to='analytics.targetgroup', verbose_name='Nhóm đối tượng'),
        ),
    ]
