# Generated by Django 6.0.6 on 2026-06-25 04:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên báo cáo')),
                ('comparison_type', models.CharField(choices=[('units', 'Giữa các đơn vị'), ('years', 'Giữa các năm'), ('groups', 'Giữa nhóm đối tượng')], max_length=50, verbose_name='Kiểu so sánh')),
                ('report_data', models.JSONField(verbose_name='Dữ liệu báo cáo')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('export_file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='File xuất (PDF/Excel)')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey', verbose_name='Khảo sát gốc')),
            ],
            options={
                'verbose_name': 'Báo cáo so sánh',
                'verbose_name_plural': 'Báo cáo so sánh',
            },
        ),
        migrations.CreateModel(
            name='ScoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên bộ chỉ số')),
                ('criteria_mapping', models.JSONField(verbose_name='Ánh xạ điểm (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang áp dụng')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey', verbose_name='Áp dụng cho khảo sát')),
            ],
            options={
                'verbose_name': 'Cấu hình chấm điểm',
                'verbose_name_plural': 'Cấu hình chấm điểm',
            },
        ),
        migrations.CreateModel(
            name='AggregatedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('city', 'Thành phố'), ('department', 'Sở/Ngành'), ('district', 'Quận/Huyện'), ('ward', 'Xã/Phường'), ('unit', 'Đơn vị sự nghiệp'), ('group', 'Nhóm đối tượng')], max_length=20, verbose_name='Cấp độ phân tích')),
                ('entity_name', models.CharField(max_length=255, verbose_name='Tên thực thể')),
                ('entity_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã thực thể')),
                ('total_responses', models.PositiveIntegerField(default=0, verbose_name='Số phiếu hợp lệ')),
                ('average_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Điểm trung bình')),
                ('raw_data', models.JSONField(default=dict, verbose_name='Dữ liệu chi tiết')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Thời gian tính toán')),
                ('year', models.PositiveIntegerField(verbose_name='Năm')),
                ('quarter', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Quý')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey', verbose_name='Khảo sát')),
            ],
            options={
                'verbose_name': 'Kết quả tổng hợp',
                'verbose_name_plural': 'Kết quả tổng hợp',
                'indexes': [models.Index(fields=['survey', 'level', 'entity_name'], name='analytics_a_survey__9befcb_idx')],
                'unique_together': {('survey', 'level', 'entity_name', 'year', 'quarter')},
            },
        ),
    ]
