# Generated by Django 6.0.6 on 2026-06-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('survey', '0005_surveyassignment_surveyparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã nhóm')),
                ('name', models.CharField(max_length=255, verbose_name='Tên nhóm')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('icon', models.CharField(choices=[('bi-person-badge', '👤 Lãnh đạo'), ('bi-shield-check', '🛡️ Chuyên trách'), ('bi-display', '💻 CNTT'), ('bi-building', '🏢 Đơn vị'), ('bi-people', '👥 Nhóm'), ('bi-person-workspace', '🧑\u200d💼 Cán bộ')], default='bi-people', max_length=50, verbose_name='Icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('forms', models.JSONField(blank=True, default=list, verbose_name='Danh sách biểu mẫu được gán')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('surveys', models.ManyToManyField(blank=True, related_name='target_groups_m2m', to='survey.survey', verbose_name='Khảo sát áp dụng')),
            ],
            options={
                'verbose_name': 'Nhóm đối tượng',
                'verbose_name_plural': 'Nhóm đối tượng',
                'ordering': ['-created_at'],
            },
        ),
    ]
