# Generated by Django 6.0.6 on 2026-07-08 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_targetgroup'),
        ('survey', '0009_surveyunitstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetgroup',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.surveycategory', verbose_name='Danh mục khảo sát'),
        ),
    ]
