# Generated by Django 6.0.6 on 2026-06-25 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên loại')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã code')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon')),
                ('has_options', models.BooleanField(default=True, verbose_name='Có options?')),
                ('has_validation', models.BooleanField(default=False, verbose_name='Có validation?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Loại câu hỏi',
                'verbose_name_plural': 'Loại câu hỏi',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề khảo sát')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug (URL thân thiện)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('start_date', models.DateTimeField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateTimeField(verbose_name='Ngày kết thúc')),
                ('allow_after_deadline', models.BooleanField(default=False, verbose_name='Cho phép trả lời sau hạn?')),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('active', 'Đang hoạt động'), ('closed', 'Đã đóng'), ('archived', 'Đã lưu trữ')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('target_groups', models.JSONField(blank=True, default=list, verbose_name='Nhóm đối tượng mục tiêu')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Cài đặt nâng cao')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Đợt khảo sát',
                'verbose_name_plural': 'Đợt khảo sát',
            },
        ),
        migrations.CreateModel(
            name='SurveyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tên danh mục')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Danh mục khảo sát',
                'verbose_name_plural': 'Danh mục khảo sát',
            },
        ),
        migrations.CreateModel(
            name='Blocklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('ip', 'IP Address'), ('email', 'Email'), ('device', 'Device ID'), ('user', 'User ID')], max_length=20, verbose_name='Loại chặn')),
                ('value', models.CharField(max_length=255, verbose_name='Giá trị bị chặn')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Lý do chặn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Hết hạn chặn')),
            ],
            options={
                'verbose_name': 'Danh sách đen',
                'verbose_name_plural': 'Danh sách đen',
                'unique_together': {('block_type', 'value')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Tiêu đề câu hỏi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả/Hướng dẫn')),
                ('is_required', models.BooleanField(default=True, verbose_name='Bắt buộc trả lời')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='Danh sách lựa chọn (JSON)')),
                ('condition_logic', models.JSONField(blank=True, default=dict, verbose_name='Logic điều kiện')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Cấu hình nâng cao')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='survey.questiontype', verbose_name='Loại câu hỏi')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.survey', verbose_name='Thuộc khảo sát')),
            ],
            options={
                'verbose_name': 'Câu hỏi',
                'verbose_name_plural': 'Danh sách câu hỏi',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='survey',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.surveycategory', verbose_name='Danh mục'),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP người trả lời')),
                ('respondent_device_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID thiết bị')),
                ('respondent_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email người trả lời')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User-Agent (Trình duyệt)')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Bắt đầu lúc')),
                ('submitted_at', models.DateTimeField(auto_now=True, verbose_name='Nộp lúc')),
                ('time_taken', models.PositiveIntegerField(default=0, verbose_name='Thời gian làm bài (giây)')),
                ('answers', models.JSONField(verbose_name='Dữ liệu trả lời (JSON)')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Đã xác thực')),
                ('verification_token', models.CharField(blank=True, max_length=64, null=True, verbose_name='Token xác thực')),
                ('is_cleaned', models.BooleanField(default=False, verbose_name='Đã làm sạch')),
                ('is_duplicate', models.BooleanField(default=False, verbose_name='Là phiếu trùng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user', verbose_name='Người dùng')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='survey.survey', verbose_name='Khảo sát')),
            ],
            options={
                'verbose_name': 'Phiếu trả lời',
                'verbose_name_plural': 'Phiếu trả lời',
                'indexes': [models.Index(fields=['survey', 'submitted_at'], name='survey_resp_survey__5eac70_idx'), models.Index(fields=['respondent_ip', 'respondent_device_id'], name='survey_resp_respond_addc01_idx'), models.Index(fields=['is_cleaned', 'is_duplicate'], name='survey_resp_is_clea_29ef78_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['slug', 'status'], name='survey_surv_slug_b1e903_idx'),
        ),
    ]
