# Generated by Django 6.0.6 on 2026-06-25 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="VD: A, B, C... dùng để hiển thị nhãn 'PHẦN A'", max_length=10, verbose_name='Mã phần')),
                ('title', models.CharField(max_length=255, verbose_name='Tên phần')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả phần')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Icon')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Phần khảo sát',
                'verbose_name_plural': 'Danh sách phần',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='survey',
        ),
        migrations.AddField(
            model_name='response',
            name='section_progress',
            field=models.JSONField(blank=True, default=dict, verbose_name='Tiến độ từng phần (%)'),
        ),
        migrations.AddField(
            model_name='response',
            name='status',
            field=models.CharField(choices=[('draft', 'Bản nháp'), ('submitted', 'Đã nộp')], default='draft', max_length=20, verbose_name='Trạng thái phiếu'),
        ),
        migrations.AlterField(
            model_name='response',
            name='answers',
            field=models.JSONField(default=dict, verbose_name='Dữ liệu trả lời (JSON)'),
        ),
        migrations.AlterField(
            model_name='response',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Nộp lúc'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['survey', 'status'], name='survey_resp_survey__bc9fe9_idx'),
        ),
        migrations.AddField(
            model_name='section',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='survey.survey', verbose_name='Thuộc khảo sát'),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.section', verbose_name='Thuộc phần'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('survey', 'code')},
        ),
    ]
