# Generated by Django 6.0.6 on 2026-06-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_seed_question_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='component_type',
            field=models.CharField(default='question', help_text='question, title, paragraph, section_break, personal_info', max_length=50, verbose_name='Loại thành phần'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['component_type'], name='survey_ques_compone_07dab6_idx'),
        ),
    ]
