# Generated by Django 6.0.6 on 2026-06-29 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('survey', '0004_question_component_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_code', models.CharField(max_length=20, verbose_name='Mã biểu mẫu (BM-03, BM-04, BM-05...)')),
                ('form_name', models.CharField(max_length=255, verbose_name='Tên biểu mẫu')),
                ('form_description', models.TextField(blank=True, null=True, verbose_name='Mô tả biểu mẫu')),
                ('target_group_code', models.CharField(max_length=50, verbose_name='Mã nhóm đối tượng')),
                ('target_group_name', models.CharField(max_length=255, verbose_name='Tên nhóm đối tượng')),
                ('target_group_description', models.TextField(blank=True, null=True, verbose_name='Mô tả nhóm đối tượng')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='survey.section', verbose_name='Phần khảo sát tương ứng')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='survey.survey', verbose_name='Khảo sát')),
            ],
            options={
                'verbose_name': 'Phân công khảo sát',
                'verbose_name_plural': 'Phân công khảo sát',
                'ordering': ['order'],
                'unique_together': {('survey', 'form_code', 'target_group_code')},
            },
        ),
        migrations.CreateModel(
            name='SurveyParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=255, verbose_name='Đơn vị công tác')),
                ('target_group_code', models.CharField(max_length=50, verbose_name='Mã nhóm đối tượng')),
                ('target_group_name', models.CharField(max_length=255, verbose_name='Tên nhóm đối tượng')),
                ('full_name', models.CharField(max_length=255, verbose_name='Họ và tên')),
                ('position', models.CharField(max_length=255, verbose_name='Chức vụ')),
                ('department', models.CharField(max_length=255, verbose_name='Bộ phận công tác')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('assigned_forms', models.JSONField(default=list, verbose_name='Biểu mẫu được gán')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('session_key', models.CharField(blank=True, max_length=64, null=True, verbose_name='Session Key')),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('submitted', 'Đã nộp'), ('expired', 'Hết hạn'), ('cancelled', 'Đã hủy')], default='draft', max_length=20, verbose_name='Trạng thái')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian nộp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant_info', to='survey.response', verbose_name='Phiếu trả lời')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='survey.survey', verbose_name='Khảo sát')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_participations', to='accounts.user', verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Người tham gia khảo sát',
                'verbose_name_plural': 'Người tham gia khảo sát',
                'indexes': [models.Index(fields=['survey', 'email'], name='survey_surv_survey__ef19be_idx'), models.Index(fields=['survey', 'session_key'], name='survey_surv_survey__11b93f_idx'), models.Index(fields=['survey', 'target_group_code'], name='survey_surv_survey__f9460a_idx')],
            },
        ),
    ]
