# Generated by Django 6.0.6 on 2026-06-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_surveyassignment_surveyparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Mã biểu mẫu'),
        ),
    ]
