# Generated by Django 6.0.6 on 2026-07-01 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_survey_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_code', models.CharField(max_length=20, verbose_name='Mã biểu mẫu')),
                ('status', models.CharField(choices=[('not_started', 'Chưa bắt đầu'), ('in_progress', 'Đang làm'), ('completed', 'Đã hoàn thành'), ('expired', 'Hết hạn')], default='not_started', max_length=20, verbose_name='Trạng thái')),
                ('progress_percent', models.PositiveIntegerField(default=0, verbose_name='Tiến độ (%)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Bắt đầu lúc')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Hoàn thành lúc')),
                ('last_accessed_at', models.DateTimeField(auto_now=True, verbose_name='Truy cập lần cuối')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='survey.surveyparticipant', verbose_name='Người tham gia')),
                ('response', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress', to='survey.response', verbose_name='Phiếu trả lời')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='survey.survey', verbose_name='Khảo sát')),
            ],
            options={
                'verbose_name': 'Tiến độ khảo sát',
                'verbose_name_plural': 'Tiến độ khảo sát',
                'ordering': ['created_at'],
                'unique_together': {('participant', 'form_code')},
            },
        ),
    ]
