# Generated by Django 6.0.6 on 2026-07-01 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_surveyprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyprogress',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_progresses', to='survey.survey', verbose_name='Khảo sát'),
        ),
    ]
