# Generated by Django 6.0.6 on 2026-07-05 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_target_groups'),
        ('survey', '0008_alter_surveyprogress_survey'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyUnitStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Chưa hoàn thành'), ('in_progress', 'Đang làm'), ('completed', 'Đã hoàn thành'), ('expired', 'Quá hạn')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('completed_count', models.PositiveIntegerField(default=0, verbose_name='Số người đã hoàn thành')),
                ('total_assignees', models.PositiveIntegerField(default=0, verbose_name='Tổng số người được gán')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian hoàn thành')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_statuses', to='accounts.organization', verbose_name='Đơn vị')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_statuses', to='survey.survey', verbose_name='Đợt khảo sát')),
            ],
            options={
                'verbose_name': 'Trạng thái đơn vị khảo sát',
                'verbose_name_plural': 'Trạng thái đơn vị khảo sát',
                'indexes': [models.Index(fields=['survey', 'status'], name='survey_surv_survey__5013f5_idx'), models.Index(fields=['organization', 'status'], name='survey_surv_organiz_a8ae25_idx')],
                'unique_together': {('survey', 'organization')},
            },
        ),
    ]
