# Generated by Django 6.0.6 on 2026-07-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_surveyunitstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='code',
            field=models.CharField(help_text="VD: A, B, C... dùng để hiển thị nhãn 'PHẦN A'", max_length=50, verbose_name='Mã phần'),
        ),
    ]
